#!/usr/bin/env bash
ETHERNET="eno1"
WIFI="wlp4s0"
STATUS=$(nmcli | grep $WIFI | awk 'FNR==1' | awk '{print $2}')

interface=$WIFI
# if wifi disconnnected check ethernet
if [ "$STATUS" = "disconnected" ]; then
    STATUS=$(nmcli | grep $ETHERNET | awk 'FNR==1' | awk '{print $2}')
    interface=$ETHERNET
fi
SSID=$(iwgetid | awk -F '"' '{ print $2 }')
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)
toggle() {
    if [[ $STATUS == "connected" ]]; then
        nmcli radio wifi off
        notify-send --icon=window-close --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
    else
        nmcli radio wifi on
        notify-send --icon=checkmark --urgency=normal "Wi-Fi" "Wi-Fi has been turned on, you are back online!"
    fi
}

icon() {
    if [[ $STATUS == "connected" ]]; then
        if [[ $interface == $WIFI ]];
        then
            if [[ "$STRENGTH" -ge "75" ]]; then
                echo ""
            elif [[ "$STRENGTH" -ge "50" ]]; then
                 echo ""
            elif [[ "$STRENGTH" -ge "25" ]]; then
                echo ""
            elif [[ "$STRENGTH" -ge "0" ]]; then
                echo ""
            else
                echo ""
            fi
        else
            echo ""
        fi
    else
        echo ""
    fi
}

status() {
    if [[ $STATUS == "connected" ]]; then
        if [[ $interface == $WIFI ]];then
        echo "$SSID"
        else
        echo "Ethernet"
        fi
    else
        echo Disconnected
    fi
}

class(){
    if [[ $STATUS == "connected" ]]; then
        echo ""
    else
        echo ""
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
elif [[ $1 == "--class" ]]; then
    class
fi
