#! /bin/sh

sleep 10 && $HOME/.config/bspwm/scripts/bspfloat floating 5 &> $HOME/.log.bspfloat.txt &
polybar &
pgrep -x sxhkd > /dev/null || sxhkd &
eww daemon &
$HOME/.config/conky/Auva/start.sh &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xfce4-power-manager &
bash $HOME/.config/bspwm/scripts/fix-plank
xsetroot -cursor_name left_ptr &
picom &
feh --bg-fill ~/.wallpapers/pixelart_night_train_cozy_gas_RoyalNaym.png
ukui-window-switch &
#parcellite &
#plank &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 
bspc config border_width         0
bspc config window_gap          20
bspc config border_radius	15

# bspc config normal_border_color \#c0caf5
# bspc config active_border_color \#c0caf5
# bspc config focused_border_color \#c0caf5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config top_padding 70
bspc config bottom_padding 25
bspc config gapless_monocle      true
# bspc config external_rules_command ~/.config/bspwm/scripts/external_rules
# bspc rule -a Peek state=floating
bspc rule -a Termite state=floating center=true rectangle=800x600+0+0
bspc rule -a "1Password" state=floating center=true rectangle=1200x900+0+0


# # add rule for googlechrome to be floating
# bspc rule -a google-chrome-stable state=floating
# bspc rule -a conky-manager2 state=floating
# bspc rule -a Kupfer.py focus=on
